### ISSUE TITLE
Products - Fitted Hat - there is only black hats available. Please update product in shop area.

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Maverick-2018#18]

**Comment by ccmorris** [comment]
Are you saying there should be no product for white hats?

**Comment by tgascoigne14** [comment]
Sorry. Correct - they will not have white hats available for a while so we need to disable the white hat

**Comment by ccmorris** [comment]
In that case it makes sense to set the available stock to 0?

**Comment by tgascoigne14** [comment]
I think that is a reasonable solution. Thanks!

**Comment by ccmorris** [comment]
fixed in content
